/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { parseDateTime } from "../runtime";
import type { StatusDfaEnum } from "./StatusDfaEnum";
import { StatusDfaEnumFromJSON, StatusDfaEnumToJSON } from "./StatusDfaEnum";

/**
 *
 * @export
 * @interface KerberosSourceSync
 */
export interface KerberosSourceSync {
    /**
     *
     */
    readonly pk: string;
    /**
     *
     */
    readonly tasks: Array<string>;
    /**
     *
     */
    readonly startedAt: Date;
    /**
     *
     */
    readonly finishedAt: Date | null;
    /**
     *
     */
    status?: StatusDfaEnum;
    /**
     *
     */
    source: string;
    /**
     *
     */
    usersCount?: number;
}

/**
 * Check if a given object implements the KerberosSourceSync interface.
 */
export function instanceOfKerberosSourceSync(value: object): value is KerberosSourceSync {
    if (!("pk" in value) || value["pk"] === undefined) return false;
    if (!("tasks" in value) || value["tasks"] === undefined) return false;
    if (
        (!("startedAt" in (value as Record<string, any>)) &&
            !("started_at" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["startedAt"] === undefined &&
            (value as Record<string, any>)["started_at"] === undefined)
    )
        return false;
    if (
        (!("finishedAt" in (value as Record<string, any>)) &&
            !("finished_at" in (value as Record<string, any>))) ||
        ((value as Record<string, any>)["finishedAt"] === undefined &&
            (value as Record<string, any>)["finished_at"] === undefined)
    )
        return false;
    if (!("source" in value) || value["source"] === undefined) return false;
    return true;
}

export function KerberosSourceSyncFromJSON(json: any): KerberosSourceSync {
    return KerberosSourceSyncFromJSONTyped(json, false);
}

export function KerberosSourceSyncFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): KerberosSourceSync {
    if (json == null) {
        return json;
    }
    return {
        pk: json["pk"],
        tasks: json["tasks"],
        startedAt:
            json["started_at"] == null ? json["started_at"] : parseDateTime(json["started_at"]),
        finishedAt: json["finished_at"] == null ? null : parseDateTime(json["finished_at"]),
        status: json["status"] == null ? undefined : StatusDfaEnumFromJSON(json["status"]),
        source: json["source"],
        usersCount: json["users_count"] == null ? undefined : json["users_count"],
    };
}

export function KerberosSourceSyncToJSON(json: any): KerberosSourceSync {
    return KerberosSourceSyncToJSONTyped(json, false);
}

export function KerberosSourceSyncToJSONTyped(
    value?: Omit<KerberosSourceSync, "pk" | "tasks" | "startedAt" | "finishedAt"> | null,
    ignoreDiscriminator: boolean = false,
): any {
    if (value == null) {
        return value;
    }

    return {
        status: StatusDfaEnumToJSON(value["status"]),
        source: value["source"],
        users_count: value["usersCount"],
    };
}
