/* tslint:disable */
/* eslint-disable */
/**
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2026.11.0-rc1
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const StatusDfaEnum = {
    Running: "running",
    Error: "error",
    Warning: "warning",
    Done: "done",
    UnknownDefaultOpenApi: "11184809",
} as const;
export type StatusDfaEnum = (typeof StatusDfaEnum)[keyof typeof StatusDfaEnum];

export function instanceOfStatusDfaEnum(value: any): boolean {
    for (const key in StatusDfaEnum) {
        if (Object.prototype.hasOwnProperty.call(StatusDfaEnum, key)) {
            if (StatusDfaEnum[key as keyof typeof StatusDfaEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StatusDfaEnumFromJSON(json: any): StatusDfaEnum {
    return StatusDfaEnumFromJSONTyped(json, false);
}

export function StatusDfaEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusDfaEnum {
    return json as StatusDfaEnum;
}

export function StatusDfaEnumToJSON(value?: StatusDfaEnum | null): any {
    return value as any;
}

export function StatusDfaEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): StatusDfaEnum {
    return value as StatusDfaEnum;
}
